# Generated by Django 3.1.2 on 2020-10-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201007_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='tname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
